language: cpp

compiler:
  - clang
  - gcc

install: 
  - sudo apt-get install cmake
  - cmake -version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

branches:
  only:
    - master

os:
  - linux
  - osx