language: cpp

compiler:
  - clang
  - gcc

sudo: required

install: 
  -chmod +x ./setup-travis.sh
  -sudo ./setup-travis.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

branches:
  only:
    - master

os:
  - linux
  - osx