language: cpp

compiler:
  - clang
  - gcc
 
install: ./setup-travis.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

branches:
  only:
    - master

os:
  - linux
  - osx